#!/usr/bin/env python3
"""Emit rtl/note_inc_rom.vh (a Verilog function with a 128-entry case table)
from the FROZEN literal synth_ref.NOTE_INC (contract Appendix A).  The RTL's
table is therefore the same bytes the reference model uses; the cocotb bench
still checks NOTE_ON at many notes end-to-end, so the ROM wiring is verified.
Run:  python3 rtl/gen_tables.py
"""
import hashlib, os, sys

here = os.path.dirname(os.path.abspath(__file__))
_default_ref = os.path.join(os.path.dirname(here), "spec", "reference")
sys.path.insert(0, os.environ.get("SYNTH_REF_DIR", _default_ref))
import synth_ref as S
h = hashlib.sha256(",".join(str(x) for x in S.NOTE_INC).encode()).hexdigest()
with open(os.path.join(here, "note_inc_rom.vh"), "w") as f:
    f.write("// GENERATED by gen_tables.py from synth_ref.NOTE_INC (contract rev %d). DO NOT EDIT.\n" % S.CONTRACT_REV)
    f.write("// sha256(NOTE_INC decimal, comma-joined) = %s\n" % h)
    # an always @* case block (a Verilog function left its argument as a dangling X-assigned
    # wire in the yosys netlist, which OpenROAD turned into an unroutable constant net)
    f.write("// reads  wire [6:0] note_inc_idx  (declare it before the include); drives note_inc_val\n")
    f.write("reg [23:0] note_inc_val;\nalways @* begin\n    case (note_inc_idx)\n")
    for i, v in enumerate(S.NOTE_INC):
        f.write("        7'd%d: note_inc_val = 24'h%06X;\n" % (i, v))
    f.write("        default: note_inc_val = 24'h000000;\n    endcase\nend\n")
print("wrote note_inc_rom.vh sha256", h)

h2 = hashlib.sha256(",".join(str(x) for x in S.SINE_Q).encode()).hexdigest()
with open(os.path.join(here, "sine_q_rom.vh"), "w") as f:
    f.write("// GENERATED by gen_tables.py from synth_ref.SINE_Q (contract rev %d, Appendix B). DO NOT EDIT.\n" % S.CONTRACT_REV)
    f.write("// sha256(SINE_Q decimal, comma-joined) = %s\n" % h2)
    f.write("// reads  wire [8:0] sine_q_idx  (declare it before the include); drives sine_q_val\n")
    f.write("reg [15:0] sine_q_val;\nalways @* begin\n    case (sine_q_idx)\n")
    for i, v in enumerate(S.SINE_Q):
        f.write("        9'd%d: sine_q_val = 16'h%04X;\n" % (i, v & 0xFFFF))
    f.write("        default: sine_q_val = 16'h0000;\n    endcase\nend\n")
print("wrote sine_q_rom.vh sha256", h2)
